### ISSUE TITLE
Videos in low quality

### ISSUE THREAD

**Issue by SuperMobile9** [fireattack/weiboPicDownloader#3]
All videos are downloaded at 360p maximum
*No problem with pics in HD

**Comment by fireattack** [comment]
Sorry, I somehow didn't get any email from issues of this repo and totally overlooked it... It's now fixed in 9d22054a77720db9aa14c74ed7c71e3fcaa0343a

Edit: "now", not "not".

**Comment by fireattack** [comment]
After 52e88701812f6cbc9aaf888dd40deb9bbd9844f2 it can download 1080p video too. 

But keep in mind Weibo takes some time to encode 1080p variant. So if you downloaded too early it wouldn't be available.
